AllCops:
  Exclude:
    - ./db
    - ./node_modules

AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Style/ClassAndModuleChildren:
  Enabled: false
